### ISSUE TITLE
GNU GPL 默认给予转载授权

### ISSUE THREAD

**Issue by andrewrunxiyu** [CN-ARC/Mindustry-CN-ARC#46]
“不鼓励传播到国外！未经授权请不要转载或搬运到任何游戏平台或论坛！允许在Q群内传播”

Mindustry 的版权许可使用 GNU General Public License。您不是游戏的原版权所有者，基于 GPL 的第七款，您不能添加这种限制。GPL 自动取消这个限制，这样说是无意义的并可能违反版权法。

**Comment by BugTD** [comment]
fork了mindustry就请尊重GNU GPL，请把“请不要“改为”不鼓励“

**Comment by runxiyu** [comment]
此外，请参见[京民终471号 柚子（北京）移动技术有限公司等与数字天堂（北京）网络技术有限公司二审民事判决书](https://wenshu.court.gov.cn/website/wenshu/181107ANFZ0BXSK4/index.html?docId=3c0957c9b82e456eb6ceab0d002c50ba)

**Comment by squi2rel** [comment]
也没强制不让啊 你想转还是可以转

**Comment by runxiyu** [comment]
> 如果需要公开发布你自行修改的版本，请联系Lucky Clover

这个也有问题

> 也没强制不让啊 你想转还是可以转

> You may not impose any further restrictions on the exercise of the rights granted or affirmed under the License.

**Comment by runxiyu** [comment]
> 授权

这也不对呀

**Comment by squi2rel** [comment]
还是直接删了好 这个原来是为了防止到处乱传的
