### ISSUE TITLE
report maybe BUG

### ISSUE THREAD

**Issue by iwillkillcaoyu** [CN-ARC/Mindustry-CN-ARC#78]
[crash-report-02_21_2024_18_31_34.txt](https://github.com/CN-ARC/Mindustry-CN-ARC/files/14358243/crash-report-02_21_2024_18_31_34.txt)
当我进入维泽服时，客户端崩溃报错了，希望解决，谢谢

**Comment by squi2rel** [comment]
30780中此问题应修复
