### ISSUE TITLE
着陆动画

### ISSUE THREAD

**Issue by hamabi314159** [CN-ARC/Mindustry-CN-ARC#84]
着陆动画会被自动跳过（不会真的有人喜欢看着陆动画吧）

**Comment by ShZxy** [comment]
设置里有可以选择开启的

**Comment by ShZxy** [comment]
设置＞图形与画面＞(翻到最下面)跳过核心发射与着陆动画

**Comment by hamabi314159** [comment]
不是设置问题，是黄队着陆会自动跳过前摇。其他队伍好像没有这个问题（玩自定义游戏发现的）
